# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95d795689c6d611aefda9bc561e06986254fdb7938f1d2085dd1c9106635ab96b74dff854709b1c2d0976d7e061874bae8a972657332d6f6a1c45054a5cd1b4d

test:
  secret_key_base: 8917b8be57c6f567140c9bf7fce0ee0a5670e4d4809bdb3b00b12720ff60c35760d36ea7b053e2e92aa3e414fb80b22d673fd8d28a6a3b8a57bfcfa286336598

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
